config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "/restaurants", to: "restaurants#index"
  get "/restaurants/new", to: "restaurants#new"
  post "/restaurants", to: "restaurants#create"
  get "/restaurants/:id", to: "restaurants#show", as: "restaurant"
  get "/restaurants/:id/edit", to: "restaurants#edit", as: "restaurant_edit"
  patch "/restaurants/:id", to: "restaurants#update"
  delete "restaurants/:id", to: "restaurants#destroy", as: "delete"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params["id"])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(strong_params)
    redirect_to restaurant_path(@restaurant)
  end

  def edit
    @restaurant = Restaurant.find(params["id"])
  end

  def update
    @restaurant = Restaurant.find(params["id"])
    @restaurant.update(strong_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params["id"])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def strong_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCrud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<h1>Edit <%= @restaurant.name %> Info</h1>

<%= form_with model: @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  <%= f.submit %>
<% end %>
<h3><%= link_to "Back", :back %></h3>

app/views/restaurants/index.html.erb
<div class="m-5">
  <h1>Restaurants List</h1>
  <h2><%= link_to "Create Restaurant", restaurants_new_path, class: "btn btn-primary" %></h2>
  <ul class="list-group">
    <% @restaurants.each do |restaurant| %>
      <li><%= link_to restaurant.name, restaurant_path(restaurant), class: "list-group-item", style: "width: 300px" %></li>
    <% end %>
  </ul>
</div>

app/views/restaurants/new.html.erb
<h1>Create New Restaurant</h1>

<%= form_with model: @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  <%= f.submit %>
<% end %>
<h3><%= link_to "Back", :back %></h3>

app/views/restaurants/show.html.erb
<h1>Restaurant Detail</h1>

<h2>Name: <%= @restaurant.name %></h2>
<h2>Address: <%= @restaurant.address %></h2>
<h2>Rating: <%= "⭐" * @restaurant.rating%></h2>

<h3><%= link_to "Edit", restaurant_edit_path(@restaurant) %></h3>
<h3><%= link_to "Delete", delete_path(@restaurant), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%></h3>
<h3><%= link_to "Back", restaurants_path %></h3>